### ISSUE TITLE
Doesn't work with types derived from map[string]interface{}

### ISSUE THREAD

**Issue by Danprot** [simonnilsson/ask#2]
Doesn't work with types derived from map[string]interface{}
like
`type MyMap map[string]interface{}`
would be nice to support it

**Comment by simonnilsson** [comment]
Hi @Danprot, please check out the latest release v0.3.0. This should now be supported. Minimum Go version is bumped to 1.17 though.

**Comment by Danprot** [comment]
works fine, thanks!
